
package vista;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.JTableHeader;


public class FormSelect extends javax.swing.JFrame {

    // Nuevo formulario FormSelect
    public FormSelect() {
        initComponents();
        populateJtable();
        
          jTable1_USERS.setShowGrid(true);
        
        jTable1_USERS.setGridColor(Color.YELLOW);
        
        jTable1_USERS.setSelectionBackground(Color.gray);
        
        JTableHeader th = jTable1_USERS.getTableHeader();

        th.setFont(new Font("Tahoma", Font.PLAIN, 16));
        // Crea un grupo de botones para los botones de opción.       
    }
 
     // Función para rellenar la jtable con datos de los usuarios.
    public void populateJtable(){
        //MVC
        controlador.Users user = new controlador.Users();
        ArrayList<controlador.Users> userList = user.UsersList();
        
        String[] colNames = {"Id","Username","password","fullname","Tel","Gender","Picture"};
     
        Object[][] rows = new Object[userList.size()][7];
       // El orden debe ser como está en el constructor de la clase para este caso Users
        for(int i = 0; i < userList.size(); i++){
            rows[i][0] = userList.get(i).getId();
            rows[i][1] = userList.get(i).getUsername();
            rows[i][2] = userList.get(i).getPassword();
            rows[i][3] = userList.get(i).getFullname();                    
            rows[i][4] = userList.get(i).getPhone();
            rows[i][5] = userList.get(i).getGender();
            // Manejo de la imagen en una tabla table no base de datos
          ImageIcon pic = new ImageIcon(new ImageIcon
                                          (userList.get(i).getPicture())
                                           .getImage()
                                           .getScaledInstance(120, 80, Image.SCALE_SMOOTH));            
           rows[i][6] = pic;
        }
         modelo.MyTableModel mmd = new modelo.MyTableModel(rows, colNames);
       jTable1_USERS.setModel(mmd);
        jTable1_USERS.setRowHeight(80);
        jTable1_USERS.getColumnModel().getColumn(6).setPreferredWidth(120); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_USERS = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jScrollPane1.setViewportView(jTable1_USERS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSelect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_USERS;
    // End of variables declaration//GEN-END:variables
}
