
package vista;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class Home_Form extends javax.swing.JFrame {

    // Nuevo formulario Home_Form
     
    public Home_Form() {
        initComponents();
        ImageIcon imgThisImg = new ImageIcon("src\\imagenes\\adsi.jpg");

        jLabel_BackgroundImage.setIcon(imgThisImg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_BackgroundImage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_PRODUCTO = new javax.swing.JMenu();
        jMenu1_ORDENES = new javax.swing.JMenu();
        jMenuItem1_INGRESARORDEN = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1_CRUDPORDUCTOS = new javax.swing.JMenuItem();
        jMenu_CATEGORIA = new javax.swing.JMenu();
        jMenu_CLIENTES = new javax.swing.JMenu();
        jMenu_USUARIO = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("menu");

        jMenu_PRODUCTO.setBackground(new java.awt.Color(249, 105, 14));
        jMenu_PRODUCTO.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_PRODUCTO.setText("PRODUCTO |");
        jMenu_PRODUCTO.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenu1_ORDENES.setText("ORDENES");

        jMenuItem1_INGRESARORDEN.setText("INGRESAR ORDEN");
        jMenuItem1_INGRESARORDEN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1_INGRESARORDENMouseClicked(evt);
            }
        });
        jMenuItem1_INGRESARORDEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_INGRESARORDENActionPerformed(evt);
            }
        });
        jMenu1_ORDENES.add(jMenuItem1_INGRESARORDEN);

        jMenu_PRODUCTO.add(jMenu1_ORDENES);

        jMenu1.setText("GESTIÓN");

        jMenuItem1_CRUDPORDUCTOS.setText(" CRUD");
        jMenuItem1_CRUDPORDUCTOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1_CRUDPORDUCTOSMouseClicked(evt);
            }
        });
        jMenuItem1_CRUDPORDUCTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_CRUDPORDUCTOSActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1_CRUDPORDUCTOS);

        jMenu_PRODUCTO.add(jMenu1);

        jMenuBar1.add(jMenu_PRODUCTO);
        jMenu_PRODUCTO.getAccessibleContext().setAccessibleName("PRODUCTO ");

        jMenu_CATEGORIA.setBackground(new java.awt.Color(249, 105, 14));
        jMenu_CATEGORIA.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_CATEGORIA.setText("CATEGORIA |");
        jMenu_CATEGORIA.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuBar1.add(jMenu_CATEGORIA);

        jMenu_CLIENTES.setBackground(new java.awt.Color(249, 105, 14));
        jMenu_CLIENTES.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_CLIENTES.setText("CLIENTES |");
        jMenu_CLIENTES.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuBar1.add(jMenu_CLIENTES);

        jMenu_USUARIO.setBackground(new java.awt.Color(249, 105, 14));
        jMenu_USUARIO.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_USUARIO.setText("USUARIO |");
        jMenu_USUARIO.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenu_USUARIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_USUARIOMouseClicked(evt);
            }
        });
        jMenu_USUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_USUARIOActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_USUARIO);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_BackgroundImage, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_BackgroundImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_USUARIOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_USUARIOMouseClicked
        // TODO add your handling code here:
            vista.Admin_Users_Form userForm = new vista.Admin_Users_Form();
                userForm.pack();
                userForm.setVisible(true);
                userForm.setLocationRelativeTo(null);
                userForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenu_USUARIOMouseClicked

    private void jMenu_USUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_USUARIOActionPerformed
        // TODO add your handling code here:
          vista.Admin_Users_Form userForm = new vista.Admin_Users_Form();
                userForm.pack();
                userForm.setVisible(true);
                userForm.setLocationRelativeTo(null);
                userForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jMenu_USUARIOActionPerformed

    private void jMenuItem1_INGRESARORDENMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1_INGRESARORDENMouseClicked
        // TODO add your handling code here:
          // TODO add your handling code here:
           /*  vista.MANAGE_ORDERS_FORM mOrdersForm = new MANAGE_ORDERS_FORM();
                mOrdersForm.pack();
                mOrdersForm.setVisible(true);
                mOrdersForm.setLocationRelativeTo(null);
                mOrdersForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);*/
        
        
    }//GEN-LAST:event_jMenuItem1_INGRESARORDENMouseClicked

    private void jMenuItem1_INGRESARORDENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_INGRESARORDENActionPerformed
        // TODO add your handling code here:
        
         /*   vista.MANAGE_ORDERS_FORM mOrdersForm = new MANAGE_ORDERS_FORM();
                mOrdersForm.pack();
                mOrdersForm.setVisible(true);
                mOrdersForm.setLocationRelativeTo(null);
                mOrdersForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        */
        
    }//GEN-LAST:event_jMenuItem1_INGRESARORDENActionPerformed

    private void jMenuItem1_CRUDPORDUCTOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1_CRUDPORDUCTOSMouseClicked
        // TODO add your handling code here:
        
       /*  vista.MANAGE_PRODUCTS_FORM mProductosForm = new vista.MANAGE_PRODUCTS_FORM();
                mProductosForm.pack();
                mProductosForm.setVisible(true);
                mProductosForm.setLocationRelativeTo(null);
                mProductosForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        */
        
        
    }//GEN-LAST:event_jMenuItem1_CRUDPORDUCTOSMouseClicked

    private void jMenuItem1_CRUDPORDUCTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_CRUDPORDUCTOSActionPerformed
        // TODO add your handling code here:
        
     /*    vista.MANAGE_PRODUCTS_FORM mProductosForm = new vista.MANAGE_PRODUCTS_FORM();
                mProductosForm.pack();
                mProductosForm.setVisible(true);
                mProductosForm.setLocationRelativeTo(null);
                mProductosForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        */
    }//GEN-LAST:event_jMenuItem1_CRUDPORDUCTOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel_BackgroundImage;
    private javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu1_ORDENES;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1_CRUDPORDUCTOS;
    private javax.swing.JMenuItem jMenuItem1_INGRESARORDEN;
    private javax.swing.JMenu jMenu_CATEGORIA;
    private javax.swing.JMenu jMenu_CLIENTES;
    private javax.swing.JMenu jMenu_PRODUCTO;
    public javax.swing.JMenu jMenu_USUARIO;
    // End of variables declaration//GEN-END:variables
}
